### ISSUE TITLE
Timeline for provider 

### ISSUE THREAD

**Issue by dressedfez** [claranet/terraform-azurerm-db-postgresql-flexible#1]
We tried yesterday your terraform module for a [standard postgres database](https://registry.terraform.io/modules/claranet/db-postgresql/azurerm/latest). The approach seems to be promising
for us, however, we would be more interested in the implementation of the flexible postgres database.

Do you have any timeline for this project?

**Comment by BzSpi** [comment]
Hi @dressedfez 

Thanks for your interest. 
The module is in development and is mostly done. To be fully transparent, we need to reintegrate the Terraform provider used in the "standard" module for user creation implemented a few weeks ago and a peer review to release it.

Unfortunately, I'm not able to provide a ETA since we mostly focus on our customer delivery but it shouldn't be that long.

**Comment by dressedfez** [comment]
@BzSpi thanks for the fast feedback. I will watch your project. If possible (needs to be clarified internally) we could help you in a testing phase.

**Comment by rossifumax** [comment]
Hello @dressedfez !

The module is just released in `v5.0.0` ! :tada: 

Feel free to test it and open issues / PRs if needed.

Have a good day !
